class_name World01Routes
## Generated by tools/levelgen/world_01.py: the intended solution of each
## World 01 level, as the player-centre x (tiles) of every tap.

## Awakening
const LEVEL_01: PackedFloat32Array = [24.4, 33.2, 40.9, 49.6, 60.2, 82.4, 91.6, 98.6, 104.8, 116.6, 142.4, 144.5, 158.6, 162.9, 193.4, 195.7, 202.9, 208.4, 217.6, 221.4]


## The route of level [param index] (0-based).
static func get_route(index: int) -> PackedFloat32Array:
	var all: Array[PackedFloat32Array] = [LEVEL_01]
	return all[index]
