class_name World03Routes
## Generated by tools/levelgen/world_03.py: the intended solution of each
## World 03 level, as the player-centre x (tiles) of every tap.

## First Flip
const LEVEL_01: PackedFloat32Array = [19, 38.822, 46.331, 80.82, 89.618, 94.609, 108.751, 133.197, 142.496]


## The route of level [param index] (0-based).
static func get_route(index: int) -> PackedFloat32Array:
	var all: Array[PackedFloat32Array] = [LEVEL_01]
	return all[index]
