[versions]
agp = "9.1.1"
kotlin = "2.2.10"
kotlinxSerialization = "1.9.0"
junit = "4.13.2"
robolectric = "4.16.1"
androidAll = "14-robolectric-10818077"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
android-all = { group = "org.robolectric", name = "android-all", version.ref = "androidAll" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
