#!/usr/bin/env python3
"""World 01 — THE RED VOID: five levels, generated.

    python3 tools/levelgen/world_01.py            # build, check, write all levels
    python3 tools/levelgen/world_01.py 3 --windows # one level, with tap windows

Writes levels/world_01/level_0N.tscn + .tres and tests/support/world_01_routes.gd.
Every obstacle's phase is fitted against the intended route (the player's
taps), with the lazy alternative (skipping the tap) required to die.
"""
import os
import sys

from levelgen import Level, T

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..") + "/"


def level_01():
    """AWAKENING — hard tutorial: gates, a slow windmill, gaps, a moving
    platform, the first double jump. Single ideas first, pairs in the
    middle, and a last fifth that asks for all of it at once."""
    lv = Level("level_01", "w01_l01", "Awakening", "Hard tutorial", 1.0)

    lv.group("Runway")
    lv.block(-12, 26, 0)
    for x in (9, 11, 13):
        lv.shard(x, 0.5)
    # A barrier with its window at the floor: the opening is the way through.
    lv.gate(19, [(1.4, 2.8)])
    lv.shard(19, 0.5)

    lv.group("FirstGap")
    lv.tap(24.4)
    lv.block(29.5, 51, 0)
    lv.shards_along(25.4, 28.4, 1.5)

    lv.group("RaisedWindow")
    lv.tap(33.2)
    lv.gate(36.2, [(2.45, 2.3)])
    lv.shard(36.2, 2.2)

    lv.group("PulseGate")
    lv.tap(40.9)
    g = lv.gate(43.8, [(1.35, 2.7), (2.7, 2.4)], hold=0.8, move=0.3)
    lv.fit_phase(g, lazy=[lv.without(40.9)])
    lv.shard(43.8, 2.2)

    lv.group("SecondGap")
    lv.tap(49.6)
    lv.block(55, 80, 0)
    lv.shards_along(50.6, 53.6, 1.5)

    lv.group("Windmill")
    lv.tap(60.2)
    a = lv.arm(63.2, 0.5, 1.6, speed=1.5, arms=2)
    lv.fit_phase(a, lazy=[lv.without(60.2)])
    lv.shard(63.2, 3.0)

    lv.checkpoint(68)

    # ------------------------------------------------ pairs: 68 .. 128 ---
    lv.group("Elevator")
    lv.block(80, 84, 0)
    lv.tap(82.4)
    period = 2.4
    lv.mover(87.5, 5, -0.5, (0, 2.25), period, lv.osc_phase(88.2, period, 0.02))
    lv.tap(91.6)
    lv.block(96.5, 112, 1.0)
    lv.shards_along(83.5, 93.5, 2.0)

    lv.group("GateAfterLanding")
    lv.tap(98.6)
    g = lv.gate(101.5, [(2.35, 2.7), (3.7, 2.4)], hold=0.7, move=0.25)
    lv.fit_phase(g, lazy=[lv.without(98.6)])

    lv.group("SecondWindmill")
    lv.tap(104.8)
    a = lv.arm(107.8, 1.5, 1.6, speed=-2.0, arms=2)
    lv.fit_phase(a, lazy=[lv.without(104.8)])

    lv.group("WindowOverGap")
    lv.block(112, 118, 0)
    lv.tap(116.6)
    lv.block(122, 145, 0)
    lv.gate(120.4, [(2.65, 2.3)])
    lv.shards_along(117.5, 121.5, 1.0)

    lv.checkpoint(128)

    # ------------------------------------------ double jump: 128 .. 182 ---
    lv.group("DoubleJumpWall")
    lv.tap(142.4, 144.5)
    lv.block(147.5, 160, 3.5)
    lv.shards_along(143, 147, 1.0)

    lv.group("DoubleJumpGap")
    lv.tap(158.6, 162.9)
    lv.block(168.5, 174, 3.5)
    lv.block(174, 209.5, 0)
    lv.shards_along(160, 167, 1.4)

    lv.checkpoint(182)

    # ----------------------------------------- the last fifth: 182 .. 232 ---
    lv.group("HighWindow")
    lv.tap(193.4, 195.7)
    lv.gate(198.5, [(4.2, 2.4)])
    lv.shard(198.5, 4.0)

    lv.group("ThirdWindmill")
    lv.tap(202.9)
    a = lv.arm(205.9, 0.5, 1.7, speed=1.9, arms=2)
    lv.fit_phase(a, lazy=[lv.without(202.9)])

    lv.group("PulseOverGap")
    lv.tap(208.4)
    lv.block(213.5, 219, 0)
    g = lv.gate(212.6, [(2.6, 2.2), (1.2, 2.4)], hold=0.6, move=0.25)
    lv.fit_phase(g, lazy=[lv.without(208.4)])

    lv.group("FinalDoubleGap")
    lv.tap(217.6, 221.4)
    g = lv.gate(223.2, [(3.9, 2.6), (2.2, 2.6)], hold=0.6, move=0.25)
    lv.fit_phase(g, lazy=[lv.without(221.4)])
    lv.block(226.5, 250, 0)

    lv.finish(238)
    return lv


LEVELS = [level_01]


def write_routes(levels):
    lines = ["class_name World01Routes",
             "## Generated by tools/levelgen/world_01.py: the intended solution of each",
             "## World 01 level, as the player-centre x (tiles) of every tap.", ""]
    for i, lv in enumerate(levels, start=1):
        taps = ", ".join(f"{x:g}" for x in sorted(lv.route))
        lines.append(f"## {lv.name}")
        lines.append(f"const LEVEL_{i:02d}: PackedFloat32Array = [{taps}]")
    names = ", ".join(f"LEVEL_{i:02d}" for i in range(1, len(levels) + 1))
    lines += ["", "", "## The route of level [param index] (0-based).",
              "static func get_route(index: int) -> PackedFloat32Array:",
              f"\tvar all: Array[PackedFloat32Array] = [{names}]",
              "\treturn all[index]"]
    with open(ROOT + "tests/support/world_01_routes.gd", "w") as fh:
        fh.write("\n".join(lines) + "\n")


def write_world(count):
    lines = ['[gd_resource type="Resource" script_class="WorldData" format=3]', "",
             '[ext_resource type="Script" path="res://src/level/world_data.gd" id="1_world"]',
             '[ext_resource type="Script" path="res://src/level/level_data.gd" id="2_level"]']
    for i in range(1, count + 1):
        lines.append(f'[ext_resource type="Resource" path="res://levels/world_01/level_{i:02d}.tres" id="level_{i:02d}"]')
    refs = ", ".join(f'ExtResource("level_{i:02d}")' for i in range(1, count + 1))
    lines += ["", "[resource]", 'script = ExtResource("1_world")', 'id = &"world_01"', "number = 1",
              'display_name = "The Red Void"', f'levels = Array[ExtResource("2_level")]([{refs}])']
    lines.append('next_world_name = "World 02"')
    with open(ROOT + "levels/world_01/world_01.tres", "w") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    args = sys.argv[1:]
    only = [int(a) for a in args if a.isdigit()]
    built = []
    for i, build in enumerate(LEVELS, start=1):
        lv = build()
        built.append(lv)
        if only and i not in only:
            continue
        taps = [int(t) for a in args if a.startswith("--taps=") for t in a[7:].split(",")]
        lv.report(windows="--windows" in args or bool(taps), only=taps or None)
        for note in lv.notes:
            print("  " + note)
        os.makedirs(ROOT + "levels/world_01", exist_ok=True)
        lv.write(ROOT, f"levels/world_01/level_{i:02d}.tscn", f"levels/world_01/level_{i:02d}.tres")
    write_routes(built)
    write_world(len(built))


if __name__ == "__main__":
    main()
